import { Storage } from "./storage.entity";
import { Price } from "./price.entity";
import { SoftDelete } from "src/AllEntites/HelperEntites/SoftDelete.entites";
import { SubCategory } from "src/AllEntites";
import { ProductMetadata } from "./productMetaData";
export declare class AllPhone extends SoftDelete {
    id: number;
    name: string;
    image: string | null;
    technology: string | null;
    bands2g: string | null;
    bands3g: string | null;
    bands4g: string | null;
    bands5g: string | null;
    speed: string | null;
    announced: string | null;
    status: string | null;
    dimensions: string | null;
    weight: string | null;
    build: string | null;
    sim: string | null;
    type: string | null;
    size: string | null;
    resolution: string | null;
    protection: string | null;
    features: string | null;
    video: string | null;
    loudspeaker: string | null;
    jack35mm: string | null;
    wlan: string | null;
    bluetooth: string | null;
    positioning: string | null;
    nfc: string | null;
    radio: string | null;
    usb: string | null;
    sensors: string | null;
    price: string | null;
    subCategory: SubCategory;
    metadata: ProductMetadata[];
    storage: Storage[];
    prices: Price[];
}
