import { Role } from 'src/roles/entities/role.entity';
import { UserCredential } from 'src/users/entities/UserCredential.entities';
import { User } from '../users/entities/user.entity';
import { Category } from 'src/category/entities/category.entity';
import { SubCategory } from 'src/subcategory/entities/subcategory.entity';
import { AllPhone } from 'src/all-phones/entities/all-phone.entity';
import { ProductMetadata } from 'src/all-phones/entities/productMetaData';
import { Price } from 'src/all-phones/entities/price.entity';
import { Storage } from 'src/all-phones/entities/storage.entity';
declare const entities: (typeof Role | typeof User | typeof UserCredential | typeof Category | typeof SubCategory | typeof Storage | typeof AllPhone | typeof Price | typeof ProductMetadata)[];
export { Role, User, UserCredential, Category, SubCategory, AllPhone, ProductMetadata, Price, Storage };
export default entities;
