import { Role } from '../roles/entities/role.entity';
import { UserCredential } from '../users/entities/UserCredential.entities';
import { User } from '../users/entities/user.entity';
import { Category } from '../category/entities/category.entity';
import { SubCategory } from '../subcategory/entities/subcategory.entity';
import { AllPhone } from '../all-phones/entities/all-phone.entity';
import { ProductMetadata } from '../all-phones/entities/productMetaData';
import { Price } from '../all-phones/entities/price.entity';
import { Storage } from '../all-phones/entities/storage.entity';
declare const entities: (typeof Role | typeof User | typeof UserCredential | typeof Category | typeof SubCategory | typeof AllPhone | typeof Storage | typeof Price | typeof ProductMetadata)[];
export { Role, User, UserCredential, Category, SubCategory, AllPhone, ProductMetadata, Price, Storage };
export default entities;
